import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Admybrand Landing Page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} min-h-screen bg-gradient-to-br from-gray-900 via-[#101E2A] to-black text-gray-100 antialiased`}
      >
        <div className="fixed inset-0 -z-10 pointer-events-none">
          {/* Optional: Add a subtle blurred glowing gradient blob for extra aesthetics */}
          <div className="absolute right-24 top-0 w-96 h-96 bg-fuchsia-700 opacity-20 blur-3xl rounded-full pointer-events-none"></div>
          <div className="absolute left-0 bottom-0 w-80 h-80 bg-blue-800 opacity-20 blur-2xl rounded-full pointer-events-none"></div>
        </div>
        {children}
      </body>
    </html>
  );
}
